### ISSUE TITLE
Method declaration doesn't match with Interface

### ISSUE THREAD

**Issue by mattsches** [middlewares/http-authentication#1]
Version: 0.5.0

I've just done a `composer update` of a early-stage project, and after that, I got the following error:

`PHP Fatal error:  Declaration of Middlewares\BasicAuthentication::process(Psr\Http\Message\ServerRequestInterface $request, Interop\Http\Server\RequestHandlerInterface $handler): Psr\Http\Message\ResponseInterface must be compatible with Psr\Http\Server\MiddlewareInterface::process(Psr\Http\Message\ServerRequestInterface $request, Psr\Http\Server\RequestHandlerInterface $handler): Psr\Http\Message\ResponseInterface in /path/to/project/vendor/middlewares/http-authentication/src/BasicAuthentication.php on line 11`

Ok, after a bit of digging around: Possible solution found [here](https://github.com/http-interop/http-server-middleware/blob/master/README.md) … but you're probably already aware of that ;)

**Comment by oscarotero** [comment]
Yes.
While this problem is not solved, you can force to use v1.0.1 of http-interop/http-server-middleware

**Comment by oscarotero** [comment]
v1.0.0 released, supporting the final version of `psr/http-server-middleware`.
If you don't want to upgrade yet, you can use `http-interop/http-server-middleware v1.1.1`.
