### ISSUE TITLE
Option to use password_verify() in basic auth

### ISSUE THREAD

**Issue by zkwbbr** [middlewares/http-authentication#2]
Currently, it looks like the only way to check if credentials are valid is by comparing the raw or hashed password to the stored version. E.g.,

```
new Middlewares\BasicAuthentication([
	'username1' => 'password1',
	'username2' => \crypt('password2', 'mysalt')
]);
```
Would be nice if we can use `password_verify()` instead? Something like this maybe:

```
$hashFromDb = $db->getPasswordHashFromUser('username1');
$authenticated = \password_verify('password1', $hashFromDb);
new Middlewares\BasicAuthentication($authenticated);
```

Edit: I don't think it's possible to hash the first example above so `\crypt()` woudn't work also. This means we have to store the password in plain text?

**Comment by oscarotero** [comment]
That's good idea.
Maybe, we can add a option to validate the password using `password_verify()`. For example:

```php
//Passwords hashes created by password_hash()
$users = [
    'username1' => '$2y$07$BCryptRequires22Chrcte/VlQH0piJtjXl.0t1XkA8pw9dMXTpOq',
];

(new Middlewares\BasicAuthentication($users))->verifyHash();
```

**Comment by zkwbbr** [comment]
@oscarotero Yup, that would be nice and clean.

**Comment by oscarotero** [comment]
New version 2.1.0 released including this feature.
